In [3]:
import pandas as pd

# Load the CSV file into a DataFrame
df_house = pd.read_csv('house.csv')
# Group by the StateName column and compute the average for each of the data columns
df_state_avg = df_house.groupby('StateName').mean().drop(columns=['RegionID', 'SizeRank'])

# Reset index for better readability
df_state_avg.reset_index(inplace=True)

df_state_avg.head()

C:\Users\birdl\AppData\Local\Temp\ipykernel_21680\3825056407.py:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_state_avg = df_house.groupby('StateName').mean().drop(columns=['RegionID', 'SizeRank'])

,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,...,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30,2023-05-31,2023-06-30,2023-07-31
0,AK,138712.193182,138986.094550,139123.205664,139385.092256,139682.248776,139930.465020,140409.533725,140729.688435,140970.820776,...,398724.063618,397547.769258,395816.815118,394189.639623,393930.950784,395747.257471,398172.853271,400330.619463,402073.904936,403132.147924
1,AL,94932.880976,95079.114340,95206.484859,93220.900625,93522.613938,93859.715138,94224.017063,93343.953656,93654.374718,...,196141.589584,195670.953698,195199.726990,196672.498532,198689.963120,201211.841200,201984.616482,202589.546460,202958.046083,203083.572808
2,AR,70133.111683,70199.862609,70324.518070,70556.639050,70821.048254,71009.574334,71162.653204,71299.932870,71488.797720,...,157307.043491,157000.197564,156716.901813,157785.271842,159416.686633,161365.044208,162011.351344,162493.742477,162916.002030,163450.669252
3,AZ,106917.557675,107028.382687,107222.166894,107639.683497,108171.868832,108712.177823,109235.394671,109739.395817,110285.874793,...,359306.152342,356168.880147,352902.444745,350604.506627,349862.993822,351009.214238,352240.764634,353643.223811,355293.330972,357236.388282
4,CA,207732.185764,208394.758226,209273.740009,211248.986090,213568.027530,216289.959341,219352.732861,222806.909627,226417.977173,...,615622.400162,610958.715652,606445.598691,601168.345879,597420.130981,596533.190808,597851.575711,600436.017481,603800.516002,608498.859160